### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by jsit** [jsit/vim-tomorrow-theme#3]
Because of all the color approximation functions, Tomorrow takes longer than it needs to to load. 256- and 88-color palette values should be hard-coded, not calculated.

See chriskempson/vim-tomorrow-theme#46

**Comment by iiey** [comment]
I tested with in Terminal and iTerm. There are no problem with colors and the loading time reduce ~10x on my laptop :)

```
vim --startuptime report
114.259  064.138  063.730: sourcing tomorrow-night.vim      <--- before commit
059.073  006.951  006.505: sourcing tomorrow-night.vim      <--- after commit
```

~~However, It doesn't work well when I check on Ubuntu 16.04 Konsole~~
sorry, my mistake tomorrow and tomorrow-night, it does work on Konsole.

Just one thing to note, that commit vim/vim@017ba07fa2 added default 'CursorLineNr cterm=underline' which somehow very distract in my opinion. So you may consider to clear the CursorLineNr or custom it

Thank for you work!

**Comment by iiey** [comment]
However, It doesn't work well when I check on Ubuntu 16.04 Konsole

![tomorrow](https://user-images.githubusercontent.com/18628392/81473671-51e77500-9200-11ea-9c16-cf614c8aee14.png)

```
Konsole 16.04.3
echo $TERM --> xterm-256color

Vim 8.2 patch 1-695
set t_Co=256
```
